### ISSUE TITLE
Changing the content-length header results in an internal server error

### ISSUE THREAD

**Issue by czardoz** [Runscope/httpbin#219]
This URL causes an internal server error

``http://httpbin.org/response-headers?Content-Length=string``

**Comment by johnsheehan** [comment]
That's not a valid content length value. It should be a number. Also not
sure if that will be overridden or not. Can you describe more what you're
trying to do?

**Comment by sigmavirus24** [comment]
Why would you want to set a custom `Content-Length` in the first place? If you want to test misbehaving servers use `pathod`.

**Comment by czardoz** [comment]
It is a case of testing misbehaving servers and pathod seems to be the right thing to use here. Closing this issue.

**Comment by sigmavirus24** [comment]
I think we should certainly return a more informative message and a better response code though.

**Comment by czardoz** [comment]
Changing it to a number results in a 502:

```
502 Bad Gateway
The server returned an invalid or incomplete response. 
```

**Comment by sigmavirus24** [comment]
So that's an infrastructure problem with @Runscope's deployment of HTTPbin. I suspect whatever is running in front of HTTPbin is doing The Right Thing™ and assuming the service is borked when it returns a content-length different from the length of the body. I also don't think whatever that service is should be changed.

**Comment by johnsheehan** [comment]
Thanks for pinpointing that. That's coming from nginx and not something we want to change right now.
